### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by regiohelden-dev** [joeirimpan/zammad_py#129]
We (as Regiohelden) are using zammad_py in our projects.
There are a few things like package upgrade and an error handling which we would like to add to it.

Would you be interested in a collaboration on the project? or handling over the maintenance to our organization?

Kind regards

**Comment by joeirimpan** [comment]
Happy to accept PRs. :smile:

**Comment by danieleades** [comment]
i'm investigating potentially making use of this library. If I can make any contributions along the way i will.

- what minimum interpreter version are you targeting?
- would you be interested in PRs to add additional testing/linting + CI?
- any interest in migrating to `Poetry`/`pyproject.toml`?

**Comment by joeirimpan** [comment]
1. >= 3.7 looks fine to me
2. Sure.
3. Sure.
