### ISSUE TITLE
Documentation on readthedocs.io is outdated

### ISSUE THREAD

**Issue by sur5r** [joeirimpan/zammad_py#143]
Subject says it all: https://zammad-py.readthedocs.io/en/latest is listing 7e40dffa as 'latest' which is (as of today) more than 2 years old.

**Comment by joeirimpan** [comment]
I have rebuilt the RTD pages. I don't think there is any breaking changes on the api though.

**Comment by sur5r** [comment]
Thanks. There was at least one important change: The `host` parameter was changed to `url`. This pretty effectively prevents one from getting started.

**Comment by Ghost93** [comment]
@sur5r 100%, wasted an hour on this, it's kind of a breaking change, I wish it was mentioned in the release log and I saved myself an hour...
