### ISSUE TITLE
interface questions

### ISSUE THREAD

**Issue by danieleades** [joeirimpan/zammad_py#151]
Hi there!

I had a couple of questions about the interface.

- i understand that the `Pagination` object can be iterated over to find the individual objects. Is it possible to iterate over the pages themselves? how can you check when `next_page` is exhausted?
- This ones a little more specific- is it possible to filter tickets by date range?
- is it possible to add negative filter parameters (specifically `not "spam" in tags`)

**Comment by joeirimpan** [comment]
Hi @danieleades 
1. It is not possible to iterate over the pages themselves. For checking when the next_page is exhausted or not, we could possible check for 404 in the next request and do a `StopIteration`?
2. Since search API takes raw query params as it is from the user, we could filter by date range if that is possible from the API.
3. Is there a API doc link which explain this?

**Comment by danieleades** [comment]
With regard to iterating over pages, it turns out that the API just starts returning empty pages.

I wonder if it would be better if the `Pagination` object was an iterator over 'pages', rather than over individual entries. Of course that's a breaking change

**Comment by joeirimpan** [comment]
@danieleades Yes. That would be a breaking change. Zammad's official ruby lib also iterates over pagination resource and instead of pages themselves. Since Zammad doesn't provide the total count of pages, users can call next_page till API no longer returns values/404.

**Comment by danieleades** [comment]
> @danieleades Yes. That would be a breaking change. Zammad's official ruby lib also iterates over pagination resource and instead of pages themselves.

that's true. Though the pagination endpoints are marked 'beta' in the docs, so i'm guessing they're not thrilled with the API either. I also don't understand why the 'all' endpoint is paginated, but the 'search' endpoint is *not*? I know that decision is on the server side, and not the client side. What prevents me from running a search for tickets which are "open OR closed", for example, and bypassing the pagination entirely?

> Since Zammad doesn't provide the total count of pages, users can call next_page till API no longer returns values/404.

it's doable, but the construction ends up a bit clumsy. (you can check for empty, the API doesn't seem to return a 404).

the alternative would be something like

```python
for page in client.ticket.all():
    for ticket in page:
        # do thing with ticket
        continue
```

otherwise you have to mess about with things like

```python
page = client.ticket.all()

while len(page) > 0:
    for ticket in page:
        # do thing with ticket
        continue
    page = page.next_page()
```

the latter seems less intuitive to me. And certainly less discoverable without some experimentation

**Comment by joeirimpan** [comment]
Right. Can you try this out? We can consider this for major release.

**Comment by Anuril** [comment]
@danieleades: I've updated the documentation with an answer to your question...  ([See](https://zammad-py.readthedocs.io/en/latest/usage.html))

You need to send a dict with {'query':'Your Zammad search query'} 

client.ticket.search({'query': 'Search Content'})

This can then be a query like it's in zammad ([See here](https://user-docs.zammad.org/en/latest/advanced/search.html))

**Comment by Anuril** [comment]
I'll close this issue as resolved. If you experience any problems with the current version, feel free to open another issue.
