### ISSUE TITLE
readthedocs build fails because of python 2.7

### ISSUE THREAD

**Issue by Anuril** [joeirimpan/zammad_py#189]
* Zammad API Client version: 1.1.0
* Python version: 3
* Operating System: ubuntu

### Description

The Docs don't get updated because the build is failing. (See: https://readthedocs.org/projects/zammad-py/builds/19471112/) 

I think this is because of python 2.7, as when I build the docs with sphinx on python 3.8 with Sphinx v6.1.3, the docs get build successfully.

**Comment by joeirimpan** [comment]
This is fixed. Thank you
