### ISSUE TITLE
Participation in Maintaining

### ISSUE THREAD

**Issue by Anuril** [joeirimpan/zammad_py#195]
Hi Joe,

I'd like to participate in the maintenance of this package. 

Specifically, I'd like to focus on three areas: 

Versioning & package maintenance
---------------------------------------
- Package on pypi 
- Tests - improvement, providing more accurate fixture for zammad api
- Compatibility checks and information regarding Zammad Versions / Upgrades
- Project / Milestones
- Versioned Documentation

De-Generalization & Logic
--------------------
- Not all resources support a GET on their ID / Not all resources support expand=true on their GET url
- Sometimes, it feels like the package is just a much nicer version of "requests.get". F.ex, instead of calling 

```
url = 'https://ticket.example.org/api/v1/'
headers = {'username'=secrets_username, 'password'=secrets_password}
query = {'query': 'Search Content'}
result = requests.post(url=url+'tickets', headers=headers, json=query)
```

I can do 

```
query = {'query': 'Search Content'}
result = client.search(params=query)
```

I think if we would provide more Resource specific options, the module would be way easier to use. 

- Extending the Classes inherited by Resource with own constructors so they can be manipulated in memory before creating them in zammad, as well as enabling easier integration of the package, reducing the amount of reading in zammad's api documentation. 

Implement Features for Webhooks
--------------------------------------

I think it would be great if the library could also provide functions to handle webhooks. It could then be used within projects that use flask or django.
Example features: 
- provide callbacks
- publish to an event message broker
- Return Resource Instance from parsed webhook request data

Thanks for your consideration. Please let me know what you think. 

I'm available here: chris+github@cleverly.ch if you want to connect via email. I also got Discord, Telegram, Signal, Twitter, etc.

**Comment by joeirimpan** [comment]
Hi @Anuril,
Thank you for the feedback. I wrote this package while evaluating Zammad at my workplace but it did not work out for us. I can add you as a maintainer for the repo right away.

**Comment by joeirimpan** [comment]
Please send me the pypi username for adding you as a maintainer there as well

**Comment by Anuril** [comment]
@joeirimpan - Could you set up a Project and link it to the repo? I'd like to track some planned changes that imho don't need to be issues.

**Comment by joeirimpan** [comment]
Cool. Adding
