### ISSUE TITLE
Add an option to bypass SSL Cert verification

### ISSUE THREAD

**Issue by pierregm** [joeirimpan/zammad_py#206]
* Zammad API Client version: 2.0.1
* Python version: 3.10.8
* Operating System: macOS Ventura 13.2.1

### Description

By default, `requests` verifies SSL certificates but gives the possibility to ignore this verification when calling a method (eg, `requests.get(..., verify=False)`.
It would be nice if this feature was supported by `zammad_py`, for example by defining an extra `verify` kwarg (default `True`) when initializing `ZammadAPI` and passing this argument to the subsequent `get`/`post`/`put` requests.

**Comment by Anuril** [comment]
I see the utility in that, but I don't like the privacy & security implications of generally allowing this. 

What I see as an option would be that you could provide a path to a certificate file, so requests would verify the server certificate against the provided certificate, allowing for self-signed or organizational trust scenarios. 

Would that be a good middle ground?

**Comment by joeirimpan** [comment]
@pierregm You can disable it by changing the session field of ZammadAPI instance.
```python
zammad_api.session.verify = False
```
