### ISSUE TITLE
Getting additionnal info about tickets

### ISSUE THREAD

**Issue by Pierlou** [joeirimpan/zammad_py#234]
* Zammad API Client version: 3.0.0
* Python version: 3.10
* Operating System: Windows 10

### Description

Thanks for this package! I am trying to filter tickets depending on their label, and so far I have not found any way to do so, neither using `zammad_py` nor through CLI. I am wondering if it is even possible to do so, and I hope this could be a place to find an answer.

### What I Did

- CLI: 
```
curl -H "Authorization: Bearer MY_TOKEN" https://{ZAMMAD_URL}/api/v1/tickets/{TICKET_ID}
```
- zammad_py:
```
from zammad_py import ZammadAPI
client = ZammadAPI(
    url=f"https://{ZAMMAD_URL}/api/v1/",
    oauth2_token=MY_TOKEN
)
client.ticket.find(TICKET_ID)
```

Both cases return the same info (expected), but not all the characteristics that I can see on Zammad UI (for instance: content of the discussion, state of the ticket (open, closed...), labels most importantly). Are these fields accessible either through CLI and/or `zammad_py`? I also tried `client.ticket.search()`, but I am not sure [which parameters are expected](https://github.com/joeirimpan/zammad_py/blob/7f603a7633e7170f1ae6d6951e4cf5b109c0d23d/zammad_py/api.py#L248). Ideally, my endgoal is to filter tickets on their creation date (which I could do with the info I have on the `/tickets` endpoint), and on their label.

Thanks in advance!

**Comment by joeirimpan** [comment]
You can follow [this](https://user-docs.zammad.org/en/latest/advanced/search.html) to filter by state_name and creation date.

**Comment by Pierlou** [comment]
Thanks a lot for the quick response and advice. Is advanced search also available through `zammad_py` (or CLI)? I've been trying various versions of syntaxes like `client.ticket.search({'tags': 'feeback', 'created_at': '[2024-01-01 TO 2024-01-31]'})` (getting tickets which tags contain "feeback" and that have been created in January 2024) but haven't been successful so far. Is this possible/the correct syntax?
