### ISSUE TITLE
Basic usage import examples do not work

### ISSUE THREAD

**Issue by dvanhise** [joeirimpan/zammad_py#26]
* Zammad API Client version: 0.1.3
* Python version: 2.7.14, 3.6.3
* Operating System: Ubuntu

### Description

The usage examples in the readme and docs show importing the library with `from zammad_py import ZammadAPI` but that does not seem to actually work.  Instead `from zammad_py.api import ZammadAPI` is what works.

### What I Did

```# Fresh install zammad_py
pip install zammad_py
# In python CLI
>>> from zammad_py import ZammadAPI
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'ZammadAPI'
>>> from zammad_py.api import ZammadAPI
>>> ZammadAPI
<class 'zammad_py.api.ZammadAPI'>
>>> 
```

**Comment by joeirimpan** [comment]
@dvanhise 0.1.3 is old version. Releasing new version now. Please upgrade your package
