### ISSUE TITLE
X-On-Behalf-Of Header

### ISSUE THREAD

**Issue by mattronix** [joeirimpan/zammad_py#73]
Hello Joe Paul, 

Was wondering if it would be possible to add the X-On-Behalf-Of param to the API client to allow for running requests to the API on behalf of the user when using HTTP Token auth and Single Sign on.

Otherwise is it ok if i make a pull request with:
```
 self, username, password, host, http_token=None, oauth2_token=None, on_behalf_of=None,

       if self._on_behalf_of:
            self.session.headers['X-On-Behalf-Of'] = \
       '%s' % self._on_behalf_of

```
Thanks!

**Comment by joeirimpan** [comment]
@mattronix Sure. Send a PR :+1:
