### ISSUE TITLE
User/Password not optional

### ISSUE THREAD

**Issue by mattronix** [joeirimpan/zammad_py#75]
Hello Joe Paul,

When using a token i still have to set a username / password value to = 'nothing' due to it requiring those fields, is it ok to make those optional as you can also do token auth?

**Comment by joeirimpan** [comment]
cool. Make it optional.

**Comment by mattronix** [comment]
Working on this one might take me a bit :)

**Comment by joeirimpan** [comment]
https://github.com/joeirimpan/zammad_py/commit/c060361d1feb90b5d032d87119fd87d8a0aa1aa5 fixes it
