### ISSUE TITLE
Ticket Attachement

### ISSUE THREAD

**Issue by mattronix** [joeirimpan/zammad_py#76]
Quick question because of integrating ticket into a view in my app i needed a way to present the attachment to the user for inline viewing of the data now your ticket attachment function works great but i need the headers such as below (because the header i forward to the client with the metadata of the file)

My View: 
```
def attachment(request,a,b,c):
    response = requests.get('%s/api/v1/ticket_attachment/%d/%d/%d' %(zammad_url,a,b,c),stream=True)
    headers = response.raw.headers
    return HttpResponse(response.raw.data,headers)%       
```
See that i also return the headers (only the content headers really) based on the request i send to zammad, any easy way i could get that header data?

**Comment by joeirimpan** [comment]
@mattronix 
Response object will not be exposed from this api client.
The only way to get the response headers is either by monkey patching / by using requests directly.

**Comment by mattronix** [comment]
@joeirimpan, clear thank you i will use request directly or stop being lazy and make correct headers myself :)
