### ISSUE TITLE
Create Ticket

### ISSUE THREAD

**Issue by mattronix** [joeirimpan/zammad_py#77]
Hello Again,

Hope im not being silly but when i try: 
new_ticket = zammad.ticket.create({
            'title': 'some new title',
            'state': 'new',
            'priority': '2 normal',
            'owner': '-',
            'customer': 'nicole.braun@zammad.org',
            'group': 'Users',
            'article': {
                'sender': 'Customer',
                'type': 'note',
                'subject': 'some subject',
                'content_type': 'text/plain',
                'body': "some body\nnext line",
            }
})

i get a list back of alot of tickets giving me the feeling that its not actually hitting the create endpoint. 

Please let me know if i missed something.

**Comment by mattronix** [comment]
It seems like its doing a get instead of post: 

217.118.162.245 - - [12/Apr/2019:14:46:07 +0200] "GET /api/v1/tickets?expand=true HTTP/1.1" 200 11570 "-" "Zammad API Python"

This is after i do a create.

**Comment by joeirimpan** [comment]
sorry for the delay. I had to set up the zammad to check.
works just fine here
```
I, [2019-04-25T09:22:01.365587 #1089-47208831604920]  INFO -- : Started POST "/api/v1/tickets?expand=true" for 172.17.0.1 at 2019-04-25 09:22:01 +0000
I, [2019-04-25T09:22:01.369596 #1089-47208831604920]  INFO -- : Processing by TicketsController#create as */*
I, [2019-04-25T09:22:01.369741 #1089-47208831604920]  INFO -- :   Parameters: {"title"=>"some new title", "state"=>"new", "priority"=>"2 normal", "owner"=>"-", "customer"=>"nicole.braun@zamma
d.org", "group"=>"Users", "article"=>{"sender"=>"Customer", "type"=>"note", "subject"=>"some subject", "content_type"=>"text/plain", "body"=>"some body\nnext line"}, "expand"=>"true"}
I, [2019-04-25T09:22:01.520251 #1089-47208831604920]  INFO -- : Authentication against Auth::Internal for user XXXXXXXX@XXXXXXXXX.com ok.
```

**Comment by mattronix** [comment]
Can you give me a snippet of what you did so I can compare what I did wrong?

Thanks

**Comment by joeirimpan** [comment]
```python
zammad = ZammadAPI(username="XXXXXXXX@XXXXXXXXX.com", password="password", host="localhost", is_secure=False)
t = zammad.ticket.create({'title': 'some new title',
    'state': 'new',
    'priority': '2 normal',
    'owner': '-',
    'customer': 'nicole.braun@zammad.org',
    'group': 'Users',
    'article': {
    'sender': 'Customer',
    'type': 'note',
    'subject': 'some subject',
    'content_type': 'text/plain',
    'body': "some body\nnext line",
}})
print(t)
```

**Comment by Bitlanech** [comment]
Unfortunately, that wont work anymore, at least from my side.
Error:
Command raised an exception: HTTPError: 422 Client Error: Unprocessable Entity for url: https://xxxxx/api/v1/tickets?expand=true
