### ISSUE TITLE
Update Ticket Issue

### ISSUE THREAD

**Issue by mattronix** [joeirimpan/zammad_py#79]
* Zammad API Client version:  0.1.6
* Python version: 3+
* Operating System: Debian

### Description
the ticket.update function does not pass all parameters to the zammad API .

### What I Did

id = 1728,

data = {
            'id' : id,
            'title': 'some new title',
            'state': 'new',
            'priority': '2 normal',
            'owner': '-',
            'customer': 'nicole.braun@zammad.org',
            'group': 'Users',
            'article': {
                'sender': 'Customer',
                'type': 'note',
                'subject': 'some subject',
                'content_type': 'text/plain',
                'body': "some body\nnext line",
            }
        }

new_ticket = zammad.ticket.update(id, data)

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.

Zammad Logs

I, [2019-04-13T15:59:40.789162 #907-70214465288180]  INFO -- : Started PUT "/api/v1/tickets/1" for 213.219.152.139 at 2019-04-13 15:59:40 +0200
I, [2019-04-13T15:59:40.792263 #907-70214465288180]  INFO -- : Processing by TicketsController#update as */*
I, [2019-04-13T15:59:40.792366 #907-70214465288180]  INFO -- :   Parameters: {"id"=>"1"}
I, [2019-04-13T15:59:40.932145 #909-47037373600760]  INFO -- : 2019-04-13T15:59:40+0200: [Work


It seems its not passing my other parameter as if i do the request directly using python requests i get: 

I, [2019-04-13T16:01:27.726051 #907-70214503958720]  INFO -- : Started PUT "/api/v1/tickets/1" for 213.219.152.139 at 2019-04-13 16:01:27 +0200
I, [2019-04-13T16:01:27.731411 #907-70214503958720]  INFO -- : Processing by TicketsController#update as */*
I, [2019-04-13T16:01:27.731612 #907-70214503958720]  INFO -- :   Parameters: {"id"=>"1", "customer"=>"matthew@uptic.local", "article"=>{"sender"=>"Customer", "type"=>"note", "subject"=>"ipo", "content_type"=>"text/plain", "body"=>"oip"}}


```

If you can help me figure out where this issue and the create issue is from i can try to fix it but im not yet skilled enough to fix it myself

**Comment by joeirimpan** [comment]
works just fine. not able to replicate the issue.
What type of authentication are you using?

**Comment by mattronix** [comment]
API key and on behalf of user
